services:
  backend:
    build: ./nuvora-backend
    container_name: smartpark-backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql+pymysql://root:12345679@db:3306/test4"
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: admin
      SECRET_KEY: "your-super-secret-jwt-key-change-in-prod"
      SERVICE_API_KEY: "nuvora-service-key-2024-change-in-prod"
    networks:
      - smartnet
    labels:
      - "traefik.http.routers.backend-nuvora.rule=Host(`nuvora`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend-nuvora.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.backend-strip-prefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.backend-nuvora.middlewares=backend-strip-prefix"

  # vision_service:
  #   build: ./vision_service
  #   container_name: smartpark-vision
  #   environment:
  #     - STREAM_URL=http://streamservice:8000/cameras/entrada/stream
  #     - RABBITMQ_HOST=rabbitmq
  #     - RABBITMQ_PORT=5672
  #     - RABBITMQ_USER=admin
  #     - RABBITMQ_PASS=admin
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   networks:
  #     - smartnet
  #   restart: on-failure

  voice_service:
    build: ./voice_service
    container_name: smartpark-voice
    ports:
      - "8003:8003"
    environment:
      BACKEND_URL: "http://smartpark-backend:8000"
      SERVICE_API_KEY: "nuvora-service-key-2024-change-in-prod"
    depends_on:
      - backend
    networks:
      - smartnet
    restart: on-failure

  frontend:
    build: ./nuvora-frontend
    container_name: smartpark-frontend
    ports:
      - "5173:5173"
    networks:
      - smartnet
    volumes:
      - ./nuvora-frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`nuvora`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=5173"

  db:
    image: mysql:8
    container_name: smartpark-db
    environment:
      MYSQL_ROOT_PASSWORD: 12345679
      MYSQL_DATABASE: test4
    ports:
      - "3306:3306"
    networks:
      - smartnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p12345679"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: smartpark-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - smartnet
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - smartnet
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  smartnet:

volumes:
  db_data:
  rabbitmq_data:
